// Talent模块组件导出
export { default as TalentHeader } from './TalentHeader.vue'
export { default as TalentUserMenu } from './TalentUserMenu.vue'
export { default as DesignerCard } from './DesignerCard.vue'
export { default as DesignerDetailDrawer } from './DesignerDetailDrawer.vue'
export { default as DesignerFilter } from './DesignerFilter.vue'
export { default as JobCard } from './JobCard.vue'
export { default as JobDetailModal } from './JobDetailModal.vue'
export { default as JobFilter } from './JobFilter.vue'
export { default as JobApplicationModal } from './JobApplicationModal.vue'
export { default as SchoolCard } from './SchoolCard.vue'
export { default as SchoolDetailModal } from './SchoolDetailModal.vue'
export { default as SchoolFilter } from './SchoolFilter.vue'
export { default as SchoolAchievements } from './SchoolAchievements.vue'
export { default as SchoolEmployment } from './SchoolEmployment.vue'
export { default as SchoolFaculty } from './SchoolFaculty.vue'
export { default as SchoolMajors } from './SchoolMajors.vue'
export { default as SchoolStudentWorks } from './SchoolStudentWorks.vue'
